=== cboeser/PHEDEX/PhEDExWeb/DataService/requests.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://cmsweb.cern.ch/phedex" elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:pns="http://cmsweb.cern.ch/phedex">

    <complexType name="status">
    	<sequence>
    		<element name="approved" type="string" maxOccurs="1" minOccurs="1"></element>
    		<element name="disapproved" type="string" maxOccurs="1" minOccurs="1"></element>
    		<element name="pending" type="string" maxOccurs="1" minOccurs="1"></element>
    		<element name="move_pending" type="string" maxOccurs="1" minOccurs="1"></element>
    	</sequence>
    </complexType>

    <complexType name="items">
    	<sequence>
    		<element name="dataset" type="string" maxOccurs="unbounded" minOccurs="0"></element>
    		<element name="block" type="string" maxOccurs="unbounded" minOccurs="0"></element>
    	</sequence>
    </complexType>

    <complexType name="subscription">
    	<sequence>
    		<element name="items" type="pns:items" maxOccurs="unbounded" minOccurs="1"></element>
    	</sequence>
    	<attribute name="open" type="int"></attribute>
    	<attribute name="priority" type="int"></attribute>
    	<attribute name="type" type="string"></attribute>
    </complexType>

    <complexType name="request">
    	<sequence>
    		<element name="status" type="pns:status" maxOccurs="1" minOccurs="1"></element>
    		<element name="subscription" type="pns:subscription" maxOccurs="unbounded" minOccurs="1"></element>
    	</sequence>
    	<attribute name="id" type="int"></attribute>
    	<attribute name="last_update" type="float"></attribute>
    </complexType>


    <element name="phedexData" type="pns:phedexData"></element>

    <complexType name="phedexData">
    	<sequence>
    		<element name="request" type="pns:request" maxOccurs="unbounded" minOccurs="1"></element>
    	</sequence>
    </complexType>

</schema>

=== cboeser/PHEDEX/PhEDExWeb/DataService/example.xml
<phedexData xmlns="http://cmsweb.cern.ch/phedex"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://cmsweb.cern.ch/phedex requests.xsd">
	<!--  Low priority replication request -->
	<request id="1234" last_update="1060199000.0">
		<status>
			<approved>T1_RAL_MSS</approved>
			<approved>T2_London_ICHEP</approved>
			<disapproved>T2_Southgrid_Bristol</disapproved>
			<pending/>
			<move_pending/>
		</status>
		<subscription open="1" priority="0" type="replicate">
			<items>
				<dataset>/PrimaryDS1/ProcessedDS1/Tier</dataset>
				<block>/PrimaryDS2/ProcessedDS2/Tier/block</block>
			</items>
		</subscription>
	</request>
	<!--  Normal priority move request -->
	<request id="5678" last_update="1060299000.0">
		<status>
			<approved>T1_FNAL_MSS</approved>
			<disapproved/>
			<pending/>
			<move_pending>T2_MIT</move_pending>
		</status>
		<subscription open="0" priority="1" type="move">
			<items>
				<dataset>/PrimaryDS3/ProcessedDS3/Tier/block1</dataset>
				<block>/PrimaryDS4/ProcessedDS4/Tier/block2</block>
			</items>
		</subscription>
	</request>
</phedexData>
